jobs:
- name: bump-cflinuxfs3
  plan:
  - in_parallel:
    - get: eirinifs
    - get: cflinuxfs3-release
      trigger: true
  - task: bump-eirinifs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci

      inputs:
      - name: eirinifs
      - name: cflinuxfs3-release

      outputs:
      - name: eirinifs-modified

      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          cflinuxfs3_version=$(cat cflinuxfs3-release/tag)
          pushd eirinifs
          sed -i "s|FROM cloudfoundry.*|FROM cloudfoundry/cflinuxfs3:${cflinuxfs3_version}|" image/Dockerfile
          git add "image/Dockerfile"
          git config --global user.email "eirini@cloudfoundry.org"
          git config --global user.name "Come-On Eirini"
          git commit --all --message "update cflinuxfs3 version to ${cflinuxfs3_version}"
          popd

          cp -r eirinifs/. eirinifs-modified/

  - put: eirinifs
    params:
      merge: true
      repository: eirinifs-modified

- name: run-tests
  plan:
  - get: eirinifs
    trigger: true
  - task: run-integration-tests
    file: eirinifs/ci/run-integration-tests/task.yml
  on_failure: &on_failure_hook
    put: slack
    params:
      channel: '#eirini-ci'
      text: |
          <!here>

          Pipeline *$BUILD_PIPELINE_NAME* failed :cry:

          Job is *$BUILD_JOB_NAME*
          Build name is *$BUILD_NAME*
      attachments: |
                [{
                    "color": "danger",
                    "actions": [
                          {
                            "type": "button",
                            "text": "View in Concourse",
                            "url": "https://ci.flintstone.cf.cloud.ibm.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
                          }
                    ]
                }]
- name: update-eirinifs
  on_failure: *on_failure_hook
  plan:
  - in_parallel:
    - get: eirinifs
      trigger: true
      passed: [ run-tests ]
    - get: cflinuxfs3-image
      trigger: true
      params:
        skip_download: true
    - get: eirinifs-version
      params:
        bump: major
  - put: eirinifs-version
    params:
      file: eirinifs-version/version
  - put: eirinifs-image
    params:
      build: eirinifs
      dockerfile: eirinifs/image/Dockerfile
    get_params:
      rootfs: true
  - task: create-release-artefacts
    file: eirinifs/ci/create-release-artefacts/task.yml
  - task: create-release-notes
    file: eirinifs/ci/create-release-notes/task.yml
  - put: eirinifs-release
    params:
      name: eirinifs-version/version
      body: release-notes/notes
      tag: eirinifs-version/version
      tag_prefix: v
      globs:
      - eirinifs-artefacts/eirinifs.tar
      - eirinifs-artefacts/eirinifs.tar.sha256

- name: update-eirini-release
  on_failure: *on_failure_hook
  plan:
  - in_parallel:
    - get: eirinifs-release
      trigger: true
      passed: [ update-eirinifs ]
    - get: eirini-release
    - get: ci-resources
  - task: update-eirinifs-version
    input_mapping:
      eirini-release-modified: eirini-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci

      inputs:
      - name: ci-resources
      - name: eirini-release
      - name: eirinifs-release

      outputs:
      - name: eirini-release-modified

      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          eirinifs_version=$(cat eirinifs-release/tag)
          pushd eirini-release
          sed -i "s|  rootfs_version:.*|  rootfs_version: '${eirinifs_version}'|" helm/cf/values.yaml
          git add "helm/cf/values.yaml"
          git config --global user.email "eirini@cloudfoundry.org"
          git config --global user.name "Come-On Eirini"
          git commit --all --message "update eirinifs version"
          popd

          cp -r eirini-release/. eirini-release-modified/
  - put: eirini-release
    params:
      merge: true
      repository: eirini-release-modified
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook))
- name: eirinifs
  type: git
  source:
    uri: git@github.com/cloudfoundry-incubator/eirinifs.git
    private_key: ((eirinifs-private-key))
    branch: master
- name: cflinuxfs3-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cflinuxfs3
- name: cflinuxfs3-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3
- name: eirinifs-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: eirinifs
    access_token: ((github-access-token))
- name: eirinifs-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: eirinifs-release-version
    file: version
    private_key: ((github-private-key))
- name: eirini-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: develop
    private_key: ((eirini-release-private-key))
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: master
- name: eirinifs-image
  type: docker-image
  icon: docker
  source:
    repository: eirini/eirinifs
    tag: test-multi-stage
    username: ((docker_hub_user))
    password: ((docker_hub_password))
