jobs:
- name: run-tests
  plan:
  - get: eirinifs
    trigger: true
  - get: launcher
    trigger: true
  - task: run-integration-tests
    file: eirinifs/ci/run-integration-tests/task.yml
  on_failure: &on_failure_hook
    put: slack
    params:
      channel: '#eirini-ci'
      text: |
          <!here>

          Pipeline *$BUILD_PIPELINE_NAME* failed :cry:

          Job is *$BUILD_JOB_NAME*
          Build name is *$BUILD_NAME*
      attachments: |
                [{
                    "color": "danger",
                    "actions": [
                          {
                            "type": "button",
                            "text": "View in Concourse",
                            "url": "https://ci.flintstone.cf.cloud.ibm.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
                          }
                    ]
                }]
- name: update-eirinifs
  on_failure: *on_failure_hook
  plan:
  - get: eirinifs
    trigger: true
    passed: [ run-tests ]
  - get: launcher
    trigger: true
    passed: [ run-tests ]
  - get: cflinuxfs3-image
    trigger: true
  - get: eirinifs-version
    params:
      bump: major
  - put: eirinifs-version
    params:
      file: eirinifs-version/version
  - task: build eirinifs
    privileged: true
    file: eirinifs/ci/build-eirinifs/task.yml
  - put: eirinifs-release
    params:
      name: eirinifs-version/version
      tag: eirinifs-version/version
      tag_prefix: v
      globs:
      - go/src/github.com/cloudfoundry-incubator/eirinifs/image/eirinifs.tar

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook))
- name: eirinifs
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirinifs.git
    branch: master
- name: launcher
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirinifs.git
    branch: master
    paths:
    - launchcmd/launch.go
    - launcher.go
- name: cflinuxfs3-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3
- name: eirinifs-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: eirinifs
    access_token: ((github-access-token))
- name: eirinifs-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: eirinifs-release-version
    file: version
    private_key: ((github-private-key))

