#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

readonly basedir="$(cd "$(dirname "$0")/.." && pwd)"
readonly target=$1

fly --target "$target" \
  set-pipeline \
    --config "$basedir/ci/pipeline.yml" \
    --pipeline eirinifs \
    --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
    --var github-access-token="$(pass eirini/github/eirinici/access-token)" 

fly --target "$target" \
    expose-pipeline \
    --pipeline eirinifs
